### ISSUE TITLE
Launch planning

### ISSUE THREAD

**Issue by kytrinyx** [exercism/pony#1]
_Note: the launch checklist was woefully outdated, since this got created over two years ago, so I deleted it._

If you are interested in leading the charge on getting this track launched, then comment below, and I'll help get this party started based on whatever is current at the time.

We have a launch guide that we'll keep up to date with changes here: https://github.com/exercism/docs/blob/master/language-tracks/launch/README.md

**Comment by Theodus** [comment]
@kytrinyx 10 exercises have been implemented.

**Comment by kytrinyx** [comment]
@Theodus that's excellent. We'll need a couple of volunteers to help give feedback on the site, as well as a couple of people to keep an eye on PRs and issues here in the xpony repository.

If we have that, then we can update the config.json to turn the track on.

**Comment by kytrinyx** [comment]
I've updated this issue to point to our new launch guide. A bunch of things have been changing on Exercism lately, and in particular we're gearing up to release a completely new site design.

**Comment by redvers** [comment]
Aged out.  There's another checklist further up.
