### ISSUE TITLE
Fix CI

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/pony#114]
This repository's `main` branch currently does not pass all CI checks.
This makes detecting issues in PRs harder and might result in a broken track, and so is an important thing to fix.

The following CI workflows are currently failing:

https://github.com/exercism/pony/runs/3066724584
https://github.com/exercism/pony/runs/3066724581

## Tracking

https://github.com/exercism/v3-launch/issues/55

**Comment by redvers** [comment]
PR#125 will fix this.

**Comment by ErikSchierboom** [comment]
@redvers Just a little FYI: if you add `Closes #114` to the [PR's description[(https://github.com/exercism/pony/pull/125), merging that PR will automatically close this issue.

See https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue for more information.

**Comment by redvers** [comment]
Closed by #125
